apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: job-container
          image: job_market_job_service:latest
          ports:
            - containerPort: 8083
              hostPort: 8083
          envFrom:
            - secretRef:
                name: app-config
          env:
            - name: USER_SERVICE_URL
              value: http://172.22.0.8:8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"  
          imagePullPolicy: IfNotPresent

