apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  type: ClusterIP
  selector:
    app: job
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  clusterIp: 10.96.0.7
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-ingress
spec:
  rules:
    - http:
        paths:
          - path: /job
            pathType: Prefix
            backend:
              service:
                name: job-service
                port:
                  number: 8083