apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      volumes:
        - name: mockdata
          configMap:
            name: mockdata
            defaultMode: 0777
      containers:
      - name: job-market-db-fill
        image: job_market_db_fill:latest
        volumeMounts:
          - name: mockdata
            mountPath: /mockdata/config
        # command: ["sh", "-c"]
        # args:
        #   - |
        #     # Attempt to connect to database on port 80 (adjust the port as needed)
        #     echo "Trying to connect to database..."
        #     if curl -s http://postgres-service:5432; then
        #       echo "Successfully connected to database";
        #     else
        #       python3 -m db_mockdata.main -f mockdata.json
        #     fi
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"  

        imagePullPolicy: IfNotPresent

  # backoffLimit: 4
      restartPolicy: OnFailure
