services:
  job_market_db:
    container_name: job_market_database
    image: job_market_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: JobMarketDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "JobMarketDB"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - inner_network

  job_market_notification:
    container_name: job_market_notification
    image: job_market_notification
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent 172.22.0.1:8082/actuator/health | grep UP || echo 'fail'"
      interval: 20s
      timeout: 5s
      retries: 3
    depends_on:
      job_market_db_fill:
        condition: service_completed_successfully
    environment:
      DATASOURCE_URL: jdbc:postgresql://172.22.0.1:5432/JobMarketDB
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: test
      SPRING_MAIL_USERNAME: 259905@student.pwr.edu.pl
      SPRING_MAIL_PASSWORD: 'qjuz bobg wbla cryx'
    networks:
      - inner_network

  job_market_user_service:
    container_name: job_market_user_service
    image: job_market_user_service
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent 172.22.0.1:8081/actuator/health | grep UP || echo 'fail'"
      interval: 20s
      timeout: 5s
      retries: 3
    depends_on:
      job_market_db_fill:
        condition: service_completed_successfully
    env_file: .env
    environment:
      DATASOURCE_URL: jdbc:postgresql://172.22.0.1:5432/JobMarketDB
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: test
      JWT_SECRET: rjiFikUAFvIeaxaRmSy159sRrgezgBMN1S7F3Z1KmTnH8hRK1dfXdnFRbSopwhIbelOKZMYzqTtyauxgklXwALbVhZMoxwYLUlu4r8uWQhBT1sWxenJA1A8qs3CXU181
      JWT_EXPIRATIONS_S: 12000
      JWT_REFRESH_EXPIRATIONS_S: 12000

    networks:
      - inner_network

  job_market_db_fill:
    container_name: job_market_db_fill
    image: job_market_db_fill:latest
    depends_on:
      job_market_db:
        condition: service_healthy
    networks:
      - inner_network

  job_market_gateway:
    container_name: job_market_gateway
    image: job_market_gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: rjiFikUAFvIeaxaRmSy159sRrgezgBMN1S7F3Z1KmTnH8hRK1dfXdnFRbSopwhIbelOKZMYzqTtyauxgklXwALbVhZMoxwYLUlu4r8uWQhBT1sWxenJA1A8qs3CXU181
    depends_on:
      job_market_db:
        condition: service_healthy
    networks:
      - inner_network

  job_market_chat_service:
    container_name: job_market_chat
    image: job_market_chat
    environment:
      DB_HOST: 172.22.0.1
    depends_on:
      job_market_db_fill:
        condition: service_completed_successfully
    ports:
    - "8088:8088"
    networks:
      - inner_network

  job_market_job_service:
    container_name: job_market_job_service
    image: job_market_job_service
    env_file: .env
    environment:
      DATASOURCE_URL: jdbc:postgresql://172.22.0.1:5432/JobMarketDB
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: test
      USER_SERVICE_URL: http://172.22.0.1:8081
    depends_on: 
      job_market_db_fill:
        condition: service_completed_successfully
    ports:
    - "8083:8083"

    networks:
      - inner_network

  rabbitmq:
      image: rabbitmq:3.12-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - inner_network

networks:
  inner_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
