services:

  job_market_db_master:
    image: job_market_database_master
    container_name: job_market_db_master
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: JobMarketDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost all all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command:
      - "postgres"
      - "-c"
      - "config_file=/tmp/postgresql.conf"
      - "-c"
      - "hba_file=/etc/pg_hba.conf"
    volumes:
      - ./master-postgresql.conf:/tmp/postgresql.conf
      - ./pg_hba.conf:/etc/pg_hba.conf
    healthcheck:
     test: 'pg_isready -U admin --dbname=JobMarketDB'
     interval: 10s
     timeout: 5s
     retries: 5
    networks:
     - inner_network

  job_market_db_replica:
    image: job_market_database
    container_name: job_market_db_replica
    ports:
      - 5434:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    command: |
      bash -c "
      pwd
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=172.22.0.1 --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 5s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      docker-entrypoint.sh -c config_file=/etc/postgresql/postgresql.conf
      "
    depends_on:
      - job_market_db_master
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/pg_hba.conf
    healthcheck:
     test: 'pg_isready -U admin --dbname=JobMarketDB'
     interval: 10s
     timeout: 5s
     retries: 5
    networks:
     - inner_network

  job_market_notification:
    container_name: job_market_notification
    image: job_market_notification
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent 172.22.0.1:8082/actuator/health | grep UP || echo 'fail'"
      interval: 20s
      timeout: 5s
      retries: 3
    depends_on:
      job_market_db_fill:
        condition: service_completed_successfully
    env_file: 
     - .env_mail
     - .env
    networks:
      - inner_network

  job_market_user_service:
    container_name: job_market_user_service
    image: job_market_user_service
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent 172.22.0.1:8081/actuator/health | grep UP || echo 'fail'"
      interval: 20s
      timeout: 5s
      retries: 3
    depends_on:
      job_market_db_fill:
        condition: service_completed_successfully
    env_file: .env
    environment:
      JWT_SECRET: qiaDsPT4GncLYoij0zwCkvOeZIDeGKE0QlIT89SFFTyYH86xKYxWood25024CLBtHWMjnpXBuzFbO78VRA0kH1V8SR7fhAkIl8AfcnOEyEyG2vIkvmlT3muF0BCTlEju
      JWT_EXPIRATIONS_S: 12000
      JWT_REFRESH_EXPIRATIONS_S: 12000

    networks:
      - inner_network

  job_market_db_fill:
    container_name: job_market_db_fill
    image: job_market_db_fill:latest
    depends_on:
      job_market_db_master:
        condition: service_healthy
    networks:
      - inner_network

  job_market_gateway:
    container_name: job_market_gateway
    image: job_market_gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: qiaDsPT4GncLYoij0zwCkvOeZIDeGKE0QlIT89SFFTyYH86xKYxWood25024CLBtHWMjnpXBuzFbO78VRA0kH1V8SR7fhAkIl8AfcnOEyEyG2vIkvmlT3muF0BCTlEju
    networks:
      - inner_network

  job_market_chat:
    container_name: job_market_chat
    image: job_market_chat
    environment:
      DB_HOST: 172.22.0.1
    depends_on:
      job_market_db_fill:
        condition: service_completed_successfully
    ports:
    - "8088:8088"
    networks:
      - inner_network

  job_market_job_service:
    container_name: job_market_job_service
    image: job_market_job_service
    env_file: .env
    environment:
      USER_SERVICE_URL: http://172.22.0.1:8081
    depends_on: 
      job_market_db_fill:
        condition: service_completed_successfully
    ports:
    - "8083:8083"

  job_market_analytics:
    container_name: job_market_analytics
    image: job_market_analytics
    env_file: .env
    environment:
      USER_SERVICE_URL: http://172.22.0.1:8081
    depends_on: 
      job_market_db_fill:
        condition: service_completed_successfully
    ports:
    - "8089:80"


  job_market_front:
    container_name: job_market_front
    image: job_market_front
    ports:
    - "80:3000"
    networks:
      - inner_network

  rabbitmq:
      image: rabbitmq:3.12-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - inner_network

networks:
  inner_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
