apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres-master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # externalIPs:
  # - 172.22.0.2
  clusterIP: 10.96.0.2
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-service
# spec:
#   selector:
#     app.kubernetes.io/name: postgres-master
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432
#   clusterIP: 172.22.0.2
#   type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 171.22.0.2