apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: job_market_user_service:latest
          ports:
            - containerPort: 8081
              hostPort: 8081
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: DATASOURCE_URL
              value: jdbc:postgresql://172.22.0.2:5432/jobMarketDB
            - name: DATASOURCE_USERNAME
              value: admin
            - name: DATASOURCE_PASSWORD
              value: test
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"  
          imagePullPolicy: IfNotPresent

