apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: job_market_user_service:latest
          ports:
            - containerPort: 8081
              hostPort: 8081
          envFrom:
            - secretRef:
                name: app-config
          env:
            - name: JWT_EXPIRATIONS_S
              value: "12000"
            - name: JWT_REFRESH_EXPIRATIONS_S
              value: "12000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "300m"  
          imagePullPolicy: IfNotPresent

