# replica-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: your-namespace
spec:
  serviceName: "postgres-replica"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      volumes:
        - name: config-volume-slave
          configMap:
            name: postgres-slave
      containers:
        - name: postgres-replica
          image: postgres:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: test
            - name: PRIMARY_DB_IP
              value: 10.96.0.2
            - name: REPLICATION_USER
              value: admin
            - name: REPLICATION_PASSWORD
              value: test
              # pg_basebackup -h $PRIMARY_DB_IP -D /var/lib/postgresql/data/pgdata -U $REPLICATION_USER -v -P --wal-method=stream --slot=replica_slot

          command:
            - sh
            - -c
            - |
              bash -c "
              pwd
              until pg_basebackup --pgdata=/var/lib/postgresql/data -R -U $REPLICATION_USER --slot=replication_slot --host=$PRIMARY_DB_IP --port=5432
              do
              echo 'Waiting for primary to connect...'
              sleep 5s
              done
              echo 'Backup done, starting replica...'
              chmod 0700 /var/lib/postgresql/data
              docker-entrypoint.sh -c config_file=/etc/postgresql/postgresql.conf
              "
          volumeMounts:

            - name: config-volume-slave
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql-slave.conf

            - name: config-volume-slave
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "750m"  


