apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database-master
  - database-slaves
  - jobs
  - users
  - gateway
  - front
  - db_mockdata
  # - chat
  # - locust-master
  # - locust-workers
  - ../configmaps

